# Generated by Django 4.2 on 2024-10-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epica',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='epica',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='epica',
            name='estado',
            field=models.CharField(choices=[('POR_HACER', 'Por hacer'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='POR_HACER', max_length=15),
        ),
        migrations.AlterField(
            model_name='epica',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='epica',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='objetivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='bloqueadores',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('POR_HACER', 'Por hacer'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='POR_HACER', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('titulo', 'sprint_asignado'), name='unique_tarea_sprint'),
        ),
    ]
