# Generated by Django 4.2 on 2024-10-24 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum_app', '0002_alter_epica_criterios_aceptacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_asignada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
